### ISSUE TITLE
test failing on Windows

### ISSUE THREAD

**Issue by flothesof** [ToFuProject/tofu#295]
After installing from source, I'm running nosetests. 

Everything runs, except for one unit test.

```
  File "C:\Users\FL232714\Documents\GitHub\tofu\tofu\tests\tests09_tutorials\tests01_runall.py", line 20, in <module>
    _TFROOT = _HERE[:-_HERE[::-1].index('/tofu'[::-1])-len('/tofu')]
ValueError: substring not found
```

Will try to fix.

**Comment by flothesof** [comment]
It fails due to the assumption that path delimiters are the same on all platforms. 
![image](https://user-images.githubusercontent.com/2360669/69736651-3d705e00-1133-11ea-9084-58e16ee4017f.png)

**Comment by Didou09** [comment]
Fixed, in devel by PR #296

**Comment by flothesof** [comment]
Can confirm all tests run from devel 2d9b1837a126d4ad9f88b8b7779ab5ddd58a5f66.

**Comment by Didou09** [comment]
Note for the future:
We générally don't close issues once a PR on develk fixes them, we simply tag them as "Fixed in devel"

Motivations:
* Issues are finally closed only when they are solved in the last official (non-alpha) release. Until then they are still open for users who are not using a development version
* It makes life easier for us to summarize the changes in a new version. We simply collect all isues labelled "Fixed in devel" to write the changelog. And we close them after the release
