### ISSUE TITLE
Create unit tests by comparing images

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#447]
Since now we switched (or we are on the verge of switching) to ~~`pyplot`~~ `pytest`  we can use ~~`pyploy-mpl`~~  `pytest-mpl` to compare resulting images:

https://github.com/matplotlib/pytest-mpl

**Comment by Didou09** [comment]
> Since now we switched (or we are on the verge of switching) to `pyplot`

You mean `pytest `right ?

**Comment by Didou09** [comment]
Good idea !

**Comment by lasofivec** [comment]
Sorry just update the OP.

**Comment by flothesof** [comment]
Just a thought, but since this hasn’t gained much traction, I would be in favor of closing this and not doing it.
I’m not sure tofu has an interest to be pixel perfect: from my experience this would create overhead if you try to do this for many usecases. 
A better alternative in my opininion is to have a simulation benchmark that is tested everytime e.g, a high-level outcome of a simulation that has been published in the litterature and that is expected to be simulated correctly by tofu.
E.g. some figure like this one maybe for the inversion algorithms:
![image](https://user-images.githubusercontent.com/2360669/149536829-ab2e2bb2-3c73-4fda-98ac-a5ddac60b525.png)
(source: https://iopscience.iop.org/article/10.1088/1742-6596/768/1/012001/pdf)
This sort of thing should be tested not with images but by comparing values as numpy arrays.

**Comment by Didou09** [comment]
Agreed !
Thanks, closing this issue then, and maybe the current work in #603 will give us an opportunity to implement this using material that might be published in some time from now.
