### ISSUE TITLE
Tofu not building on conda-forge due to missing dependency (requests)

### ISSUE THREAD

**Issue by flothesof** [ToFuProject/tofu#557]
Hi,

as discussed with @Didou09 yesterday, conda-forge builds did not succeed due to the missing requests dependency (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=387527&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412).

The import is here: https://github.com/ToFuProject/tofu/blob/bc6c9605fe51157eb392f3e70fb4727d5be7cf2e/tofu/openadas2tofu/_requests.py#L5

Reading the docs, it seems that Requests is not part of the standard library (see install notes [here](https://docs.python-requests.org/en/latest/user/install/).

Where it gets weird is that requests is mentioned in the setup.py https://github.com/ToFuProject/tofu/blob/bc6c9605fe51157eb392f3e70fb4727d5be7cf2e/setup.py#L305

I’ll investigate more.

Florian

**Comment by Didou09** [comment]
Apparently it is already in the requirements.txt too, 
And it is also already in the 'run' section of the conda recipe,

So it seems like it is missing only in the conda-forge recipe, so waiting for your PR :-)

Thanks !

**Comment by Didou09** [comment]
The issue with Pypi is that they don't allow to delete existing files and replace them, once the files are uploaded that's it.

![image](https://user-images.githubusercontent.com/5929562/136369385-06890495-5484-4838-a13e-549ade4c233f.png)

This is the reason why we have to increment the version number every time we test the deployment workflow and sme flies get uploaded on Pypi.

So since we have already incremented a lot and some people have started downloading / using tofu 1.4.15 I'd rather wait a bit and make a new release a bit later with new features in it. 

Regarding tests and the the time they take, you're right, but it's also the price to pay to get a good coverage of the library (we're at ~60 % of the code which is tested), and since they run for each PR on Github it's safe even if contributors don't run them locally.
One workaround is that you can locally run only a subset of the tests (the ones that run on the parts you modified) by specifying the test file.



But despite all this, I beleive there is some room for improvements, I should find some time to check it but I think some of the heavier tests are a bit redundant and we can probably save 1-2 min at least.

**Comment by Didou09** [comment]
I'll try to address that for the next release, you're right, 8 min is probably too much
